### ISSUE TITLE
Vendor Form Page

### ISSUE THREAD

**Issue by GittBUB** [zednon/Project1#6]
This will be a form with basic fields. Fields that are required for the site to function:

- [x] Text box for venue name

- [x] Text box for venue street address

- [x] Text box for venue city/town

- [x] Text box for venue state

- [x] Text box for venue zip code

- [x] Text box for capacity

- [x] Text box for description

- [x] Email 

- [ ] Phone number

- [x] Image upload

- [x] Submit button

- [x] Modal upon submit

- [ ] Does the vendor get redirected to somewhere? Maybe the page they just created?

- [x] Information on this page is being sent to Firebase

For now we will leave out availability date. Just for now the vendor will post info about space and user will specify date. If the vendor is available on the date requested, then vendor will accept.

**Comment by verna100** [comment]
I'm going to go ahead and close this page. the 2 open items are phone number which we all agreed to do without and does the vendor get redirected to somewhere. as of now in the project it's no for this since the vendor inputs his info and the information goes somewhere else (list of spaces) but for now the vendor's portion thanks them for the submission and their job is done.
